stages:
  - linter
  - test
  - doc

python_linter:
  stage: linter
  tags:
    - sshroy.spike.batman
  script:
    - commit=`git rev-parse HEAD`
    - conda create --name bat_ci_$commit --clone bat_ci
    - source activate bat_ci_$commit
    - python setup.py build_fortran
    - python setup.py install
    - pycodestyle --max-line-length=120 --exclude=gp_1d_sampler.py,function*,TreeCut*,RBFnet*,tecplot* batman > pycodestyle.log || echo 0
    - cat pycodestyle.log
    - pylint batman --rcfile=setup.cfg --ignore-patterns='gp_1d_sampler.py','RBFnet.py','TreeCut.py','resampling.py' > linter.log || echo 0
    - cat linter.log
    - lint=`cat linter.log`
    - regex='at ([0-9][-.][0-9]{2})[-/]10'
    - lint_res=`[[ $lint =~ $regex ]] && echo "${BASH_REMATCH[1]}"`
    - source deactivate
    - conda remove --name bat_ci_$commit --all
    - if [[ "$lint_res" > "9.5" ]]; then exit 0; else exit 1; fi

nemo_testing_python_3:
  stage: test
  tags:
    - sshroy.spike.batman
  script:
    - commit=`git rev-parse HEAD`
    - cd ..
    - scriptdir=batman/.gitlab/continuous_integration_scripts
    - tar -cf batman_ci.tar batman
    - rsync batman_ci.tar $scriptdir/CI_NEMO.sh roy@nemo:.ci_batman/$commit
    - bash $scriptdir/CI_NEMO.sh $commit

nemo_testing_python_2:
  stage: test
  tags:
    - sshroy.spike.batman
  only:
    - master
    - develop
  script:
    - commit=`git rev-parse HEAD`
    - cd ..
    - scriptdir=batman/.gitlab/continuous_integration_scripts
    - tar -cf batman_ci_2.tar batman
    - rsync batman_ci_2.tar $scriptdir/CI_NEMO_2.sh roy@nemo:.ci_batman_2/$commit
    - bash $scriptdir/CI_NEMO_2.sh $commit

pages:
  stage: doc
  tags:
    - sshroy.spike.batman
  script:
    - commit=`git rev-parse HEAD`
    - conda create --name bat_ci_$commit --clone bat_ci
    - source activate bat_ci_$commit
    - python setup.py build_fortran
    - python setup.py install
    - cd doc
    - make html
    - rm -rf ../public
    - mv _build/html/ ../public/
    - source deactivate
    - conda remove --name bat_ci_$commit --all
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
