stages:
  - linter
  - test
  - doc

python_linter:
  stage: linter
  tags:
    - sshroy.spike.batman
  script:
    - source activate bat_ci
    - python setup.py build_fortran
    - python setup.py install
    - pycodestyle --max-line-length=120 --exclude=gp_1d_sampler.py,function*,TreeCut*,RBFnet*,tecplot* batman > pycodestyle.log || echo 0
    - cat pycodestyle.log
    - pylint batman --rcfile=setup.cfg --ignore-patterns='gp_1d_sampler.py','RBFnet.py','TreeCut.py','resampling.py' > linter.log || echo 0
    - cat linter.log
    - lint=`cat linter.log`
    - regex='at ([0-9][-.][0-9]{2})[-/]10'
    - lint_res=`[[ $lint =~ $regex ]] && echo "${BASH_REMATCH[1]}"`
    - pip uninstall -y batman
    - if [[ "$lint_res" > "9.5" ]]; then exit 0; else exit 1;fi

nemo_testing_python_3:
  stage: test
  tags:
    - sshroy.spike.batman
  script:
    - cd ../.
    - tar -cf batman_ci.tar batman
    - scp batman_ci.tar batman/CI_NEMO.sh roy@nemo:~/.
    - bash batman/CI_NEMO.sh

nemo_testing_python_2:
  stage: test
  tags:
    - sshroy.spike.batman
  only:
    - master
    - develop
  script:
    - cd ../.
    - tar -cf batman_ci_2.tar batman
    - scp batman_ci_2.tar batman/CI_NEMO_2.sh roy@nemo:~/.
    - bash batman/CI_NEMO_2.sh

pages:
  stage: doc
  tags:
    - sshroy.spike.batman
  script:
  - source activate bat_ci
  - python setup.py build_fortran
  - python setup.py install
  - cd doc
  - make html
  - rm -rf ../public
  - mv _build/html/ ../public/
  - pip uninstall -y batman
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
