stages:
  - test
  - doc

nemo_testing:
  stage: test
  tags:
    - sshroy.spike.batman
  only:
    - master
    - develop
  script:
    - cd ../.
    - tar -cf batman_ci.tar batman
    - scp batman_ci.tar batman/CI_NEMO.sh roy@nemo:~/.
    - ssh roy@nemo 'srun --partition debug --job-name batci --nodes=1 CI_NEMO.sh'

pages:
  stage: doc
  tags:
    - sshroy.spike.batman
  script:
  - source activate bat_ci
  - python setup.py build_fortran
  - python setup.py install
  - cd doc
  - make html
  - rm -rf public/
  - mv _build/html/ public/
  - pip uninstall -y batman
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
