stages:
  - linter
  - test
  - doc

python_linter:
  stage: linter
  image: "tupui/bat_ci_3"
  script:
    - python setup.py build_fortran
    - python setup.py install
    - pycodestyle --max-line-length=120 --exclude=gp_1d_sampler.py,function*,TreeCut*,RBFnet*,tecplot* batman > pycodestyle.log || echo 0
    - cat pycodestyle.log
    - pylint batman --rcfile=setup.cfg --ignore-patterns='gp_1d_sampler.py','RBFnet.py','TreeCut.py','resampling.py' > linter.log || echo 0
    - cat linter.log
    - lint=`cat linter.log`
    - regex='at ([0-9][-.][0-9]{2})[-/]10'
    - lint_res=`[[ $lint =~ $regex ]] && echo "${BASH_REMATCH[1]}"`
    - if [[ "$lint_res" > "9.5" ]]; then exit 0; else exit 1; fi

.template_python_3: &template_python_3
  stage: test
  image: "tupui/bat_ci_3"
  script:
    - scriptdir=.gitlab/continuous_integration
    - bash $scriptdir/CI.sh

python_3:
  <<: *template_python_3
  only:
    - master
    - develop

python_3_feature_branch:
  <<: *template_python_3
  when: manual
  except:
    - master
    - develop

python_2:
  stage: test
  image: "tupui/bat_ci_2"
  only:
    - master
    - develop
  script:
    - scriptdir=.gitlab/continuous_integration
    - bash $scriptdir/CI.sh

pages:
  stage: doc
  image: "tupui/bat_ci_3"
  script:
    - python setup.py build_fortran
    - python setup.py install
    - cd doc
    - make html
    - rm -rf ../public
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
