FROM alpine
FROM continuumio/miniconda3:latest

WORKDIR /app

RUN conda create -n bat_ci -c conda-forge python=2 openturns=1.9 matplotlib numpy scipy scikit-learn pathos jsonschema sphinx sphinx_rtd_theme pytest pytest-runner mock ffmpeg pycodestyle pylint coverage && rm -rf /opt/conda/pkgs/*

COPY Dockerfile_python_2 /app/

ENV PATH /opt/conda/envs/bat_ci/bin:$PATH
