name: bat_ci
channels:
- conda-forge
- defaults
dependencies:
- alabaster
- asn1crypto
- astroid
- atomicwrites
- attrs
- babel
- blas
- bzip2
- ca-certificates
- certifi
- cffi
- chardet
- cryptography
- cryptography-vectors
- cycler
- dill
- docutils
- freetype
- gettext
- gmp
- gnutls
- hmat-oss
- icu
- idna
- imagesize
- isort
- jinja2
- jsonschema
- kiwisolver
- lazy-object-proxy
- libffi
- libgfortran
- libiconv
- libpng
- libxml2
- markupsafe
- matplotlib
- mccabe
- more-itertools
- multiprocess
- muparser
- ncurses
- nettle
- nlopt
- numpy
- openblas
- openssl
- openturns
- packaging
- pandas
- paramiko
- pathos
- pbr
- pip
- pluggy
- pox
- ppft
- py
- pyasn1
- pycparser
- pygments
- pynacl
- pyopenssl
- pyparsing
- pysocks
- python
- python-dateutil
- pytz
- readline
- requests
- scikit-learn
- scipy
- setuptools
- six
- snowballstemmer
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-websupport
- sqlite
- tbb
- tk
- tornado
- typed-ast
- urllib3
- wheel
- wrapt
- x264
- xz
- zlib
- bcrypt
