version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/python:latest
    working_directory: ~/batman

workflows:
  main:
    jobs:
      - dependencies
      - linter:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies

jobs:
  dependencies:
    executor: my-executor
    steps:
      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  linter:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: |
            . venv/bin/activate
            pycodestyle --max-line-length=120 --exclude=function*,TreeCut*,RBFnet* batman > pycodestyle.log || echo 0
            cat pycodestyle.log
            pylint batman --rcfile=setup.cfg --ignore-patterns='RBFnet.py','TreeCut.py' > linter.log || echo 0
            cat linter.log
            lint=`cat linter.log`
            regex='at ([0-9][-.][0-9]{2})[-/]10'
            lint_res=`[[ $lint =~ $regex ]] && echo "${BASH_REMATCH[1]}"`
            if [[ "$lint_res" > "9.4" ]]; then exit 0; else exit 1; fi

  test:
    parallelism: 4
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Test
          command: bash .github/continuous_integration/CI.sh
          environment:
            # matplotlb backend to non-interactive
            MPLBACKEND: "Agg"

      - store_artifacts:
          path: test-reports
          destination: test-reports
