version: 2.1

orbs:
  python: circleci/python@volatile

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pycodestyle --max-line-length=120 --exclude=function*,TreeCut*,RBFnet* batman > pycodestyle.log || echo 0
            cat pycodestyle.log
            pylint batman --rcfile=setup.cfg --ignore-patterns='RBFnet.py','TreeCut.py' > linter.log || echo 0
            cat linter.log
            lint=`cat linter.log`
            regex='at ([0-9][-.][0-9]{2})[-/]10'
            lint_res=`[[ $lint =~ $regex ]] && echo "${BASH_REMATCH[1]}"`
            if [[ "$lint_res" > "9.65" ]]; then exit 0; else exit 1; fi

      - run:
          command: |
            bash .github/continuous_integration/CI.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
