#!/bin/tcsh
rm -rf *.loi *.xcas *.dtd *.geo *.lig fort.22 *.damoc
mv ResultatsListing.lis ResultatsListing.lis_old
mv ResultatsOpthyca.opt ResultatsOpthyca.opt_old
mv config_adour.json config_adour.json_old
ln -s data_adour_maritime/ParametresMascaret.xcas ParametresMascaret.xcas
ln -s data_adour_maritime/mascaret-1.0.dtd mascaret-1.0.dtd 
ln -s data_adour_maritime/Geometrie.geo Geometrie.geo
ln -s data_adour_maritime/LigneEauInitiale.lig LigneEauInitiale.lig
ln -s data_adour_maritime/Q9312510.loi Q9312510.loi
ln -s data_adour_maritime/Q3120030.loi Q3120030.loi
ln -s data_adour_maritime/Q5421020.loi Q5421020.loi
ln -s data_adour_maritime/Q7412910.loi Q7412910.loi
ln -s data_adour_maritime/Q935001001.loi Q935001001.loi
ln -s data_adour_maritime/config_adour.json config_adour.json
ln -s data_adour_maritime/config_adour_user.json config_adour_user.json
